---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: {{ .Values.analyticsService.annotations.velocityID | quote }}
    velocity.tech.v1/dependsOn: {{ .Values.analyticsService.annotations.velocityDependsOn | quote }}
  name: analytics
  labels:
    app: analytics
spec:
  selector:
    matchLabels:
      api: analytics
  replicas: 1
  template:
    metadata:
      labels:
        app: analytics
        api: analytics
    spec:
      containers:
        - name: analytics
          image: {{ .Values.analyticsService.containers.image | quote }}
          env:
            - name: MONGO2_HOST
              value: {{ .Values.analyticsService.envVars.MONGO2_HOST | quote  }}
            - name: MONGO2_PORT
              value: {{ .Values.analyticsService.envVars.MONGO2_PORT | quote  }}

          ports:
            - name: analytics
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: analytics
  selector:
    app: analytics
  type: ClusterIP
