---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: {{ .Values.blogService.annotations.velocityID | quote }}
    velocity.tech.v1/dependsOn: {{ .Values.blogService.annotations.velocityDependsOn | quote }}
  name: blog
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      api: blog
  replicas: 1
  template:
    metadata:
      labels:
        app: blog
        api: blog
    spec:
      containers:
        - name: blog
          image: {{ .Values.blogService.containers.image | quote }}
          imagePullPolicy: Always
          env:
            - name: MONGO1_HOST
              value: {{ .Values.blogService.envVars.MONGO1_HOST | quote  }}
            - name: MONGO1_PORT
              value: {{ .Values.blogService.envVars.MONGO1_PORT | quote  }}
            - name: REDIS_HOST
              value: {{ .Values.blogService.envVars.REDIS_HOST | quote  }}
            - name: REDIS_PORT
              value: {{ .Values.blogService.envVars.REDIS_PORT | quote  }}
          ports:
            - name: blog
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: blog
  selector:
    app: blog
  type: ClusterIP
