---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-worker
  labels:
    app: db-worker
spec:
  selector:
    matchLabels:
      api: db-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: db-worker
        api: db-worker
    spec:
      containers:
        - name: db-worker
          image: {{ .Values.dbWorker.containers.image | quote }}
          env:
            - name: REDIS_HOST
              value: {{ .Values.dbWorker.envVars.REDIS_HOST | quote  }}
            - name: REDIS_PORT
              value: {{ .Values.dbWorker.envVars.REDIS_PORT | quote  }}
            - name: MONGO1_HOST
              value: {{ .Values.dbWorker.envVars.MONGO1_HOST | quote  }}
            - name: MONGO1_PORT
              value: {{ .Values.dbWorker.envVars.MONGO1_PORT | quote  }}
