webAPI:
  containers:
    image: ironzin/blog-post-web-api:1.0.0
  
  envVars:
    REDIS_HOST: redis
    REDIS_PORT: "6379"
    ANALYTICS_SERVICE_HOST: analytics
    ANALYTICS_SERVICE_PORT: "8080"
    BLOG_SERVICE_HOST: blog
    BLOG_SERVICE_PORT: "8080"

  ingress:
    ingressClassName: kong
    host: null
  

dbWorker:

  containers:
    image: ironzin/blog-post-db_worker:1.0.0
  
  envVars:
    REDIS_HOST: redis
    REDIS_PORT: "6379"
    MONGO1_HOST: mongo1
    MONGO1_PORT: "27017"


blogService:

  containers:
    image: jdvincent/gin-redis-blog-service:latest
  
  envVars:
    REDIS_HOST: redis
    REDIS_PORT: "6379"
    MONGO1_HOST: mongo1
    MONGO1_PORT: "27017"


analyticsWorker:

  containers:
    image: jdvincent/gin-redis-analytics-worker:latest
  
  envVars:
    REDIS_HOST: redis
    REDIS_PORT: "6379"
    MONGO2_HOST: mongo2
    MONGO2_PORT: "27017"


analyticsService:

  containers:
    image: jdvincent/gin-redis-analytics-service:latest
  
  envVars:
    MONGO2_HOST: mongo2
    MONGO2_PORT: "27017"
