webAPI:
  annotations:
    velocityID: "web-api"
    velocityDependsOn: "redis, analytics-ser, blog-service"

  containers:
    image: jdvincent/gin-redis-web-api:latest
  
  envVars:
    REDIS_HOST: "{velocity.v1:redis.exposures(port=redis).host}"
    REDIS_PORT: "{velocity.v1:redis.exposures(port=redis).port}"
    ANALYTICS_SERVICE_HOST: analytics-ser
    ANALYTICS_SERVICE_PORT: "8080"
    BLOG_SERVICE_HOST: blog-service
    BLOG_SERVICE_PORT: "8080"

  ingress:
    ingressClassName: null
    host: "api-{velocity.v1.domainSuffix}"
  

dbWorker:
  annotations:
    velocityID: "db-worker"
    velocityDependsOn: "redis, mongo1"

  containers:
    image: jdvincent/gin-redis-db-worker:latest
  
  envVars:
    REDIS_HOST: "{velocity.v1:redis.exposures(port=redis).host}"
    REDIS_PORT: "{velocity.v1:redis.exposures(port=redis).port}"
    MONGO1_HOST: "{velocity.v1:mongo1.exposures(port=mongo1).host}"
    MONGO1_PORT: "{velocity.v1:mongo1.exposures(port=mongo1).port}"


blogService:
  annotations:
    velocityID: "blog-service"
    velocityDependsOn: "redis, mongo1"

  containers:
    image: jdvincent/gin-redis-blog-service:latest
  
  envVars:
    REDIS_HOST: "{velocity.v1:redis.exposures(port=redis).host}"
    REDIS_PORT: "{velocity.v1:redis.exposures(port=redis).port}"
    MONGO1_HOST: "{velocity.v1:mongo1.exposures(port=mongo1).host}"
    MONGO1_PORT: "{velocity.v1:mongo1.exposures(port=mongo1).port}"


analyticsWorker:
  annotations:
    velocityID: "analytics-worker"
    velocityDependsOn: "redis, mongo2"

  containers:
    image: jdvincent/gin-redis-analytics-worker:latest
  
  envVars:
    REDIS_HOST: "{velocity.v1:redis.exposures(port=redis).host}"
    REDIS_PORT: "{velocity.v1:redis.exposures(port=redis).port}"
    MONGO2_HOST: "{velocity.v1:mongo2.exposures(port=mongo2).host}"
    MONGO2_PORT: "{velocity.v1:mongo2.exposures(port=mongo2).port}"


analyticsService:
  annotations:
    velocityID: "analytics-ser"
    velocityDependsOn: "mongo2"

  containers:
    image: jdvincent/gin-redis-analytics-service:latest
  
  envVars:
    MONGO2_HOST: "{velocity.v1:mongo2.exposures(port=mongo2).host}"
    MONGO2_PORT: "{velocity.v1:mongo2.exposures(port=mongo2).port}"
